# Generated by Django 5.1.1 on 2025-01-16 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('CUSTOM', 'Custom')], default=None, max_length=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCEEDED', 'Succeeded'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
